FROM ubuntu:16.04

ENV TERM xterm

RUN apt-get update --fix-missing

#COPY files/ntopng.conf /usr/local/etc/redis/redis.conf



# Update the repository and install Redis Server
#RUN         apt-get update && apt-get install -y redis-server

# Expose Redis port 6379
#EXPOSE      6379

# Run Redis Server
#ENTRYPOINT  ["/usr/bin/redis-server"]
#CMD [ "redis-server", "/usr/local/etc/redis/ntopng.conf" ]
#CMD [ "/usr/local/etc/redis/ntopng.conf" ]
