#!/bin/sh

export TERM=xterm

echo "$(date). start" >> '/opt/bootstrap/bootstrap.log'

# check if already provisioned
if [ -f /opt/bootstrap/bootstraped.txt ] ; then
   echo 'already provisioned. Exit' >> '/opt/bootstrap/bootstrap.log'
else

   # do the work
   sleep 3
   #

   # done
   echo "$(date). finished" >> '/opt/bootstrap/bootstrap.log'
   echo '1' > '/opt/bootstrap/bootstraped.txt'

fi



###
exec /opt/kibana/bin/kibana
