FROM redis:3.2.4

COPY files/redis.conf /usr/local/etc/redis/redis.conf



# Update the repository and install Redis Server
#RUN         apt-get update && apt-get install -y redis-server

# Expose Redis port 6379
#EXPOSE      6379

# Run Redis Server
#ENTRYPOINT  ["/usr/bin/redis-server"]
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#CMD [ "/usr/local/etc/redis/redis.conf" ]
